{{- if .Values.galoyAgentsProxy.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: galoy-agents-proxy-pg-mcp
  labels:
    {{- include "galoy-deps.labels" . | nindent 4 }}
    galoy-agents-proxy/component: pg-mcp
spec:
  type: ClusterIP
  selector:
    {{- include "galoy-deps.selectorLabels" . | nindent 4 }}
    galoy-agents-proxy/component: pg-mcp
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
{{- end }}
