#@ load("@ytt:data", "data")
#@ load("pipeline-fragments.lib.yml",
#@   "testflight_job",
#@   "bump_in_deployments_job",
#@   "chart_repo_resource",
#@   "testflight_tf_resource")

groups:
- name: galoy-deps
  jobs:
  - galoy-deps-testflight
  - bump-galoy-deps-in-deployments

jobs:
- #@ testflight_job("galoy-deps", "galoy-deps")
- #@ bump_in_deployments_job("galoy-deps")

resources:
- #@ chart_repo_resource("galoy-deps")
- #@ testflight_tf_resource("galoy-deps")

- name: charts-repo
  type: git
  source:
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key

- name: pipeline-tasks
  type: git
  source:
    paths: [ci/tasks/*, ci/testflight/*, Makefile]
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key

- name: galoy-deployments
  type: git
  source:
    uri: #@ data.values.deployments_git_uri
    branch: #@ data.values.deployments_git_branch
    private_key: #@ data.values.github_private_key

resource_types:
- name: terraform
  type: registry-image
  source:
    repository: #@ data.values.docker_registry + "/terraform-resource"
    tag: latest
    username: #@ data.values.gar_registry_user
    password: #@ data.values.gar_registry_password

- name: helm
  type: docker-image
  source:
    repository: #@ data.values.docker_registry + "/helm-resource"
    tag: edge
    username: #@ data.values.gar_registry_user
    password: #@ data.values.gar_registry_password
